### ISSUE TITLE
Daemon got stuck after several hours of use. 

### ISSUE THREAD

**Issue by Martin1134** [VorpalBlade/keyboard-backlightd#6]
It's me again :D

Recently the Daemon got "stuck" and produced 100% CPU utilization and the Daemon status outputs the following: 

```
Apr 24 23:33:19 Arch-MBP keyboard-backlightd[435]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 4, path: "/dev/input/event7 (deleted)", read: true, write: true }: No such device (os er>
Apr 24 23:33:19 Arch-MBP keyboard-backlightd[435]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 3, path: "/dev/input/event10 (deleted)", read: true, write: true }: No such device (os e>
Apr 24 23:33:19 Arch-MBP keyboard-backlightd[435]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 4, path: "/dev/input/event7 (deleted)", read: true, write: true }: No such device (os er>
Apr 24 23:33:19 Arch-MBP keyboard-backlightd[435]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 3, path: "/dev/input/event10 (deleted)", read: true, write: true }: No such device (os e>
Apr 24 23:33:19 Arch-MBP keyboard-backlightd[435]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 4, path: "/dev/input/event7 (deleted)", read: true, write: true }: No such device (os er>
Apr 24 23:33:19 Arch-MBP keyboard-backlightd[435]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 3, path: "/dev/input/event10 (deleted)", read: true, write: true }: No such device (os e>
Apr 24 23:33:19 Arch-MBP keyboard-backlightd[435]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 4, path: "/dev/input/event7 (deleted)", read: true, write: true }: No such device (os er>
Apr 24 23:33:19 Arch-MBP keyboard-backlightd[435]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 3, path: "/dev/input/event10 (deleted)", read: true, write: true }: No such device (os e>
Apr 24 23:33:19 Arch-MBP keyboard-backlightd[435]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 4, path: "/dev/input/event7 (deleted)", read: true, write: true }: No such device (os er>
Apr 24 23:33:19 Arch-MBP keyboard-backlightd[435]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 3, path: "/dev/input/event10 (deleted)", read: true, write: true }: No such device (os e>
```

But devices are in the the shown paths.. 

A restart of the Daemon fixed the issue. 

EDITED your comment to use tripple backquotes for the code block for readability

**Comment by Martin1134** [comment]
And it happened again. 

![Bildschirmfoto vom 2023-04-24 23-59-31](https://user-images.githubusercontent.com/44879342/234126118-04272d74-b8a9-457c-ac87-b2338b183ae1.png)

**Comment by VorpalBlade** [comment]
For some reason the input device node has been removed and seemingly recreated? This is handled through a library (evdev-rs, which binds to libevdev), so it is not something I work with directly.

Do you know what you did to trigger this behaviour? E.g. suspend/resume, hibernate, etc? I would like to know how to attempt to reproduce this.

I imagine a workaround would be to attempt to reopen the file whenever I get that type of error.

Also a couple of notes:
* Consider using `journalctl -eu keyboard-backlightd.service | tail -n20` or similar, to get the full lines, as the ends are cut off here (scrolls sideways).
* Use <code>```</code> around code blocks on github. Like:
```
    ```
    log or code lines here
    ```
```
(with no spaces at the start of the lines, that is there in this example to make it possible to have a code block inside a code block).

**Comment by Martin1134** [comment]
`[martin@Arch-MBP ~]$ journalctl -eu keyboard-backlightd.service | tail -n20
Apr 25 11:24:00 Arch-MBP keyboard-backlightd[13989]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 3, path: "/dev/input/event7 (deleted)", read: true, write: true }: No such device (os error 19)
Apr 25 11:24:00 Arch-MBP keyboard-backlightd[13989]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 4, path: "/dev/input/event9 (deleted)", read: true, write: true }: No such device (os error 19)
Apr 25 11:24:00 Arch-MBP keyboard-backlightd[13989]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 3, path: "/dev/input/event7 (deleted)", read: true, write: true }: No such device (os error 19)
Apr 25 11:24:00 Arch-MBP keyboard-backlightd[13989]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 4, path: "/dev/input/event9 (deleted)", read: true, write: true }: No such device (os error 19)
Apr 25 11:24:00 Arch-MBP keyboard-backlightd[13989]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 3, path: "/dev/input/event7 (deleted)", read: true, write: true }: No such device (os error 19)
Apr 25 11:24:00 Arch-MBP keyboard-backlightd[13989]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 4, path: "/dev/input/event9 (deleted)", read: true, write: true }: No such device (os error 19)
Apr 25 11:24:00 Arch-MBP keyboard-backlightd[13989]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 3, path: "/dev/input/event7 (deleted)", read: true, write: true }: No such device (os error 19)
Apr 25 11:24:00 Arch-MBP keyboard-backlightd[13989]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 4, path: "/dev/input/event9 (deleted)", read: true, write: true }: No such device (os error 19)
Apr 25 11:24:00 Arch-MBP keyboard-backlightd[13989]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 3, path: "/dev/input/event7 (deleted)", read: true, write: true }: No such device (os error 19)
Apr 25 11:24:00 Arch-MBP keyboard-backlightd[13989]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 4, path: "/dev/input/event9 (deleted)", read: true, write: true }: No such device (os error 19)
Apr 25 11:24:00 Arch-MBP keyboard-backlightd[13989]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 3, path: "/dev/input/event7 (deleted)", read: true, write: true }: No such device (os error 19)
Apr 25 11:24:00 Arch-MBP keyboard-backlightd[13989]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 4, path: "/dev/input/event9 (deleted)", read: true, write: true }: No such device (os error 19)
Apr 25 11:24:00 Arch-MBP keyboard-backlightd[13989]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 3, path: "/dev/input/event7 (deleted)", read: true, write: true }: No such device (os error 19)
Apr 25 11:24:00 Arch-MBP keyboard-backlightd[13989]: [WARN  keyboard_backlightd::handlers::ev_dev] Error reading File { fd: 4, path: "/dev/input/event9 (deleted)", read: true, write: true }: No such device (os error 19)
Apr 25 11:24:29 Arch-MBP systemd[1]: Stopping Start keyboard backlight daemon...
Apr 25 11:24:29 Arch-MBP systemd[1]: keyboard-backlightd.service: Deactivated successfully.
Apr 25 11:24:29 Arch-MBP systemd[1]: Stopped Start keyboard backlight daemon.
Apr 25 11:24:29 Arch-MBP systemd[1]: keyboard-backlightd.service: Consumed 25.677s CPU time.
Apr 25 11:24:29 Arch-MBP systemd[1]: Starting Start keyboard backlight daemon...
Apr 25 11:24:29 Arch-MBP systemd[1]: Started Start keyboard backlight daemon.
`

That's the full output, I found it happens when the device comes back on from sleep.

**Comment by VorpalBlade** [comment]
I cannot reproduce your error. In addition, my attempts to simply reopen the device failed, it appears the underlying C library (libevdev) or perhaps the Rust bindings for it (evdev-rs) gets into a broken state if this is done (tested by monitoring an external USB keyboard that I would unplug and replug to simulate an IO error).

As a workaround I have ensured that the service exits with an error instead of getting stuck. Then the systemd service is now set up to restart the service on failure.

(The other option would be to attempt to change to the native rust library (evdev), but it has a completely different API, requiring a substantial rewrite, so it is something I want to avoid. And there is no guarantee that this would fix the issue anyway.)

Please test the latest git version to see if this fixes your issue.
